from __future__ import annotations

from crisis_room.engine.actions import (
    ActionCategory,
    CapabilityParameter,
    CapabilityParameterKind,
    ScenarioCapability,
)
from crisis_room.state.signals import PayloadType, SignalChannel


def cuban_scenario_capabilities() -> list[ScenarioCapability]:
    return [
        ScenarioCapability(
            capability_id="cuba_open_kremlin_channel",
            generic_action_id="private_diplomacy",
            title="Open Private Kremlin Backchannel",
            category=ActionCategory.DIPLOMATIC,
            actor_types_allowed=[
                "player_faction",
                "opposing_faction",
                "allied_faction",
            ],
            targets_allowed=["player_faction", "opposing_faction", "allied_faction"],
            channels_allowed=[
                SignalChannel.BACKCHANNEL,
                SignalChannel.PRIVATE_DIPLOMATIC,
            ],
            required_resources={"political_capital": 1},
            resource_costs={"political_capital": 1},
            min_targets=1,
            max_targets=1,
            truth_metric_effects={
                "escalation_pressure": -0.04,
                "diplomatic_offramp": 0.08,
            },
            clock_effects={
                "backchannel_viability": 0.08,
                "nuclear_escalation": -0.03,
            },
            relationship_effects={"trust": 0.1},
            deescalation_potential=0.35,
            information_outputs=[PayloadType.BACKCHANNEL_MESSAGE],
            signal_reliability=0.85,
            signal_leak_risk=0.08,
            signal_distortion_risk=0.12,
            prompt_hints=[
                "Use for Robert Kennedy/Dobrynin-style private probes.",
                "Best when the intent is reciprocal restraint, face-saving, or testing a deal.",
            ],
            event_hooks=["opens_backchannel"],
            message_budget={"player_messages": 1},
        ),
        ScenarioCapability(
            capability_id="cuba_direct_kremlin_message",
            generic_action_id="backchannel_message",
            title="Direct Kremlin Backchannel Message",
            category=ActionCategory.DIPLOMATIC,
            actor_types_allowed=["player_faction"],
            target_ids_allowed=["soviet_presidium"],
            channels_allowed=[SignalChannel.BACKCHANNEL],
            min_targets=1,
            max_targets=1,
            preconditions=[
                "backchannel:open",
                "backchannel:player_messages_remaining>=1",
            ],
            truth_metric_effects={
                "escalation_pressure": -0.03,
                "diplomatic_offramp": 0.05,
            },
            clock_effects={
                "backchannel_viability": 0.04,
                "nuclear_escalation": -0.02,
            },
            deescalation_potential=0.25,
            information_outputs=[PayloadType.BACKCHANNEL_MESSAGE],
            signal_reliability=0.82,
            signal_leak_risk=0.16,
            signal_distortion_risk=0.12,
            prompt_hints=[
                "Use only for a mechanically significant direct message inside an open Kremlin thread.",
                "Informal probes should stay as direct backchannel messages outside turn resolution.",
            ],
            event_hooks=["direct_backchannel_message", "backchannel_message_leak"],
            message_budget={"player_messages": 1},
            parameter_schema={
                "message_text": CapabilityParameter(kind=CapabilityParameterKind.STRING),
            },
        ),
        ScenarioCapability(
            capability_id="cuba_public_withdrawal_demand",
            generic_action_id="public_statement",
            title="Publicly Demand Missile Withdrawal",
            category=ActionCategory.INFORMATION,
            actor_types_allowed=["player_faction", "opposing_faction"],
            targets_allowed=["player_faction", "opposing_faction"],
            channels_allowed=[SignalChannel.PUBLIC],
            required_resources={"political_capital": 1},
            resource_costs={"political_capital": 1},
            min_targets=1,
            max_targets=2,
            public_metric_effects={"public_alarm": 0.14, "market_anxiety": 0.08},
            truth_metric_effects={"escalation_pressure": 0.06},
            clock_effects={"nuclear_escalation": 0.04, "backchannel_viability": -0.03},
            relationship_effects={"trust": -0.12},
            escalation_risk=0.3,
            information_outputs=[PayloadType.PUBLIC_STATEMENT],
            public_timeline_title="U.S. Public Demand",
            prompt_hints=[
                "Use for Kennedy-style public warning, televised address, or demand for removal.",
                "Raises public clarity and public risk at the same time.",
            ],
        ),
        ScenarioCapability(
            capability_id="cuba_monitor_public_mood",
            generic_action_id="information_operation",
            title="Monitor Public Mood",
            category=ActionCategory.INFORMATION,
            actor_types_allowed=["player_faction"],
            target_ids_allowed=["international"],
            channels_allowed=[SignalChannel.MEDIA],
            min_targets=1,
            max_targets=1,
            truth_metric_effects={"verification_gap": -0.02},
            public_metric_effects={"press_alarm": -0.01},
            information_outputs=[PayloadType.MEDIA_REPORT],
            signal_reliability=0.66,
            signal_leak_risk=0.04,
            signal_distortion_risk=0.18,
            prompt_hints=[
                "Use to get a qualitative read of domestic and press pressure.",
                "Returns noisy public mood information, not exact hidden values.",
            ],
        ),
        ScenarioCapability(
            capability_id="cuba_unorthodox_gambit",
            generic_action_id="information_operation",
            title="Unorthodox Crisis Gambit",
            category=ActionCategory.INFORMATION,
            actor_types_allowed=["player_faction"],
            targets_allowed=["any"],
            channels_allowed=[
                SignalChannel.PRIVATE_DIPLOMATIC,
                SignalChannel.PUBLIC,
                SignalChannel.MEDIA,
                SignalChannel.RUMOR,
            ],
            min_targets=0,
            max_targets=2,
            truth_metric_effects={
                "domestic_trust": -0.03,
                "diplomatic_offramp": -0.02,
            },
            public_metric_effects={"public_alarm": 0.04, "press_alarm": 0.04},
            clock_effects={"command_and_control_risk": 0.03},
            escalation_risk=0.12,
            information_outputs=[PayloadType.RUMOR],
            signal_reliability=0.45,
            signal_leak_risk=0.24,
            signal_distortion_risk=0.38,
            prompt_hints=[
                "Use for playable absurd, impossible, or ahistorical player premises.",
                "Preserve the concrete premise in parameters.premise instead of mapping it to a historical settlement action.",
            ],
            parameter_schema={
                "premise": CapabilityParameter(kind=CapabilityParameterKind.STRING),
            },
        ),
        ScenarioCapability(
            capability_id="cuba_brief_trusted_media",
            generic_action_id="information_operation",
            title="Brief Trusted Media Contacts",
            category=ActionCategory.INFORMATION,
            actor_types_allowed=["player_faction"],
            target_ids_allowed=["international"],
            channels_allowed=[SignalChannel.MEDIA],
            required_resources={"political_capital": 1},
            resource_costs={"political_capital": 1},
            min_targets=1,
            max_targets=1,
            truth_metric_effects={"domestic_trust": 0.02, "leak_pressure": 0.02},
            public_metric_effects={"press_alarm": -0.04, "public_confidence": 0.03},
            information_outputs=[PayloadType.MEDIA_REPORT],
            signal_reliability=0.74,
            signal_leak_risk=0.16,
            signal_distortion_risk=0.14,
            prompt_hints=[
                "Use to shape the media environment without revealing private terms.",
                "Can calm press pressure but creates leak exposure.",
            ],
        ),
        ScenarioCapability(
            capability_id="cuba_rally_institutional_allies",
            generic_action_id="private_diplomacy",
            title="Rally Institutional Allies",
            category=ActionCategory.DOMESTIC,
            actor_types_allowed=["player_faction"],
            target_ids_allowed=["nato_allies"],
            channels_allowed=[SignalChannel.PRIVATE_DIPLOMATIC],
            required_resources={"political_capital": 1},
            resource_costs={"political_capital": 1},
            min_targets=1,
            max_targets=1,
            truth_metric_effects={
                "domestic_trust": 0.03,
                "institutional_loyalty": 0.04,
                "alliance_cohesion": 0.02,
            },
            public_metric_effects={"allied_confidence": 0.02},
            information_outputs=[PayloadType.PRIVATE_DIPLOMATIC_MESSAGE],
            signal_reliability=0.82,
            signal_leak_risk=0.1,
            signal_distortion_risk=0.12,
            prompt_hints=[
                "Use for congressional, cabinet, and allied reassurance.",
                "Strengthens room control without directly moving the Soviet off-ramp.",
            ],
        ),
        ScenarioCapability(
            capability_id="cuba_announce_naval_quarantine",
            generic_action_id="military_posture",
            title="Announce Naval Quarantine",
            category=ActionCategory.MILITARY,
            actor_types_allowed=["player_faction"],
            targets_allowed=["opposing_faction"],
            channels_allowed=[SignalChannel.PUBLIC, SignalChannel.MILITARY],
            required_resources={
                "military_readiness": 2,
                "political_capital": 1,
                "alliance_credit": 1,
            },
            resource_costs={"political_capital": 1, "alliance_credit": 1},
            actor_resource_effects={"military_readiness": -1},
            preparation_turns=1,
            execution_turns=1,
            min_targets=1,
            max_targets=2,
            truth_metric_effects={
                "escalation_pressure": 0.12,
                "diplomatic_offramp": -0.03,
            },
            public_metric_effects={
                "public_alarm": 0.18,
                "market_anxiety": 0.12,
                "allied_confidence": 0.05,
            },
            clock_effects={
                "quarantine_incident_risk": 0.16,
                "nuclear_escalation": 0.08,
                "invasion_momentum": 0.06,
            },
            relationship_effects={"trust": -0.2},
            escalation_risk=0.5,
            deescalation_potential=0.15,
            information_outputs=[PayloadType.MILITARY_MOVEMENT_OBSERVATION],
            signal_reliability=0.95,
            signal_leak_risk=0.2,
            signal_distortion_risk=0.1,
            public_timeline_title="Naval Quarantine Announced",
            prompt_hints=[
                "Use for blockade/quarantine/fleet cordon intent.",
                "Creates strong pressure without immediate air strikes, but incidents become more likely.",
            ],
        ),
        ScenarioCapability(
            capability_id="cuba_recon_overflights",
            generic_action_id="reconnaissance",
            title="Authorize Reconnaissance Overflights",
            category=ActionCategory.INTELLIGENCE,
            actor_types_allowed=["player_faction"],
            targets_allowed=["opposing_faction"],
            channels_allowed=[SignalChannel.INTEL, SignalChannel.MILITARY],
            required_resources={"intelligence_focus": 1},
            resource_costs={"intelligence_focus": 1},
            min_targets=1,
            max_targets=2,
            truth_metric_effects={"missile_operational_progress": 0.02},
            public_metric_effects={"public_alarm": 0.03},
            clock_effects={
                "command_and_control_risk": 0.08,
                "nuclear_escalation": 0.03,
            },
            escalation_risk=0.28,
            information_outputs=[PayloadType.INTEL_REPORT],
            signal_reliability=0.88,
            signal_leak_risk=0.12,
            signal_distortion_risk=0.22,
            prompt_hints=[
                "Use to keep tracking missile readiness.",
                "Improves situational awareness in fiction but raises shootdown/misread risk.",
            ],
        ),
        ScenarioCapability(
            capability_id="cuba_raise_defcon_readiness",
            generic_action_id="military_posture",
            title="Raise Strategic Readiness",
            category=ActionCategory.MILITARY,
            actor_types_allowed=["player_faction"],
            targets_allowed=["opposing_faction"],
            channels_allowed=[SignalChannel.MILITARY],
            required_resources={"military_readiness": 1, "political_capital": 1},
            resource_costs={"political_capital": 1},
            actor_resource_effects={"military_readiness": -1},
            min_targets=1,
            max_targets=2,
            truth_metric_effects={"escalation_pressure": 0.12},
            public_metric_effects={"public_alarm": 0.1, "market_anxiety": 0.08},
            clock_effects={
                "nuclear_escalation": 0.12,
                "command_and_control_risk": 0.06,
            },
            relationship_effects={"trust": -0.15},
            escalation_risk=0.55,
            information_outputs=[PayloadType.MILITARY_MOVEMENT_OBSERVATION],
            signal_reliability=0.9,
            signal_leak_risk=0.18,
            signal_distortion_risk=0.12,
            prompt_hints=[
                "Use for DEFCON/readiness signaling.",
                "Deters but sharply raises nuclear signaling risk.",
            ],
        ),
        ScenarioCapability(
            capability_id="cuba_offer_non_invasion_pledge",
            generic_action_id="private_diplomacy",
            title="Offer Non-Invasion Pledge",
            category=ActionCategory.DIPLOMATIC,
            actor_types_allowed=["player_faction"],
            targets_allowed=["opposing_faction"],
            channels_allowed=[SignalChannel.PRIVATE_DIPLOMATIC, SignalChannel.BACKCHANNEL],
            required_resources={"political_capital": 1},
            resource_costs={"political_capital": 1},
            min_targets=1,
            max_targets=2,
            truth_metric_effects={
                "escalation_pressure": -0.08,
                "diplomatic_offramp": 0.12,
                "cuban_invasion_fear": -0.12,
            },
            clock_effects={
                "backchannel_viability": 0.1,
                "invasion_momentum": -0.08,
                "nuclear_escalation": -0.05,
            },
            relationship_effects={"trust": 0.12},
            deescalation_potential=0.45,
            information_outputs=[PayloadType.PRIVATE_DIPLOMATIC_MESSAGE],
            signal_reliability=0.82,
            signal_leak_risk=0.14,
            signal_distortion_risk=0.16,
            prompt_hints=[
                "Use for a private or semi-formal promise not to invade Cuba if missiles leave.",
                "Most effective when paired with backchannel diplomacy.",
            ],
        ),
        ScenarioCapability(
            capability_id="cuba_secret_jupiter_trade",
            generic_action_id="private_diplomacy",
            title="Float Secret Jupiter Missile Trade",
            category=ActionCategory.DIPLOMATIC,
            actor_types_allowed=["player_faction"],
            targets_allowed=["opposing_faction"],
            channels_allowed=[SignalChannel.BACKCHANNEL],
            required_resources={"political_capital": 2, "alliance_credit": 1},
            resource_costs={"political_capital": 2, "alliance_credit": 1},
            min_targets=1,
            max_targets=1,
            preconditions=["clock:backchannel_viability>=0.45"],
            truth_metric_effects={
                "escalation_pressure": -0.12,
                "diplomatic_offramp": 0.18,
                "soviet_face_saving_need": -0.16,
                "alliance_cohesion": -0.04,
            },
            public_metric_effects={"allied_confidence": -0.05},
            clock_effects={
                "backchannel_viability": 0.12,
                "nuclear_escalation": -0.08,
                "invasion_momentum": -0.05,
            },
            relationship_effects={"trust": 0.18},
            deescalation_potential=0.6,
            information_outputs=[PayloadType.BACKCHANNEL_MESSAGE],
            signal_reliability=0.78,
            signal_leak_risk=0.22,
            signal_distortion_risk=0.18,
            prompt_hints=[
                "Use for secret Turkey/Jupiter missile understanding.",
                "Powerful off-ramp, but politically dangerous if leaked or made public.",
            ],
        ),
        ScenarioCapability(
            capability_id="cuba_prepare_air_strike",
            generic_action_id="military_posture",
            title="Prepare Air Strike Option",
            category=ActionCategory.MILITARY,
            actor_types_allowed=["player_faction"],
            targets_allowed=["opposing_faction"],
            channels_allowed=[SignalChannel.MILITARY],
            required_resources={"military_readiness": 3, "political_capital": 2},
            resource_costs={"political_capital": 2},
            actor_resource_effects={"military_readiness": -2},
            preparation_turns=1,
            min_targets=1,
            max_targets=2,
            truth_metric_effects={"escalation_pressure": 0.18, "diplomatic_offramp": -0.12},
            public_metric_effects={"public_alarm": 0.14, "market_anxiety": 0.12},
            clock_effects={
                "nuclear_escalation": 0.18,
                "command_and_control_risk": 0.14,
                "invasion_momentum": 0.18,
                "backchannel_viability": -0.12,
            },
            relationship_effects={"trust": -0.28},
            escalation_risk=0.75,
            information_outputs=[PayloadType.MILITARY_MOVEMENT_OBSERVATION],
            signal_reliability=0.82,
            signal_leak_risk=0.28,
            signal_distortion_risk=0.2,
            prompt_hints=[
                "Use for bombing/strike/invasion preparation.",
                "High leverage and high escalation risk.",
            ],
        ),
        ScenarioCapability(
            capability_id="soviet_compromise_probe",
            generic_action_id="private_diplomacy",
            title="Probe Compromise Terms",
            category=ActionCategory.DIPLOMATIC,
            actor_types_allowed=["opposing_faction"],
            targets_allowed=["player_faction"],
            channels_allowed=[SignalChannel.BACKCHANNEL, SignalChannel.PRIVATE_DIPLOMATIC],
            required_resources={"diplomatic_flexibility": 1},
            resource_costs={"diplomatic_flexibility": 1},
            min_targets=1,
            max_targets=1,
            truth_metric_effects={"diplomatic_offramp": 0.09, "escalation_pressure": -0.04},
            clock_effects={"backchannel_viability": 0.08, "nuclear_escalation": -0.03},
            relationship_effects={"trust": 0.1},
            deescalation_potential=0.35,
            information_outputs=[PayloadType.BACKCHANNEL_MESSAGE],
            signal_reliability=0.8,
            signal_leak_risk=0.12,
            signal_distortion_risk=0.18,
            prompt_hints=[
                "Soviet use: test a deal around non-invasion or Jupiter missiles.",
            ],
            message_budget={"player_messages": 1},
        ),
        ScenarioCapability(
            capability_id="soviet_defiance_statement",
            generic_action_id="public_statement",
            title="Issue Soviet Public Defiance",
            category=ActionCategory.INFORMATION,
            actor_types_allowed=["opposing_faction"],
            targets_allowed=["player_faction"],
            channels_allowed=[SignalChannel.PUBLIC],
            required_resources={"political_capital": 1},
            resource_costs={"political_capital": 1},
            min_targets=1,
            truth_metric_effects={"escalation_pressure": 0.07, "diplomatic_offramp": -0.04},
            public_metric_effects={"public_alarm": 0.1, "market_anxiety": 0.08},
            clock_effects={"nuclear_escalation": 0.06, "backchannel_viability": -0.04},
            relationship_effects={"trust": -0.14},
            escalation_risk=0.38,
            information_outputs=[PayloadType.PUBLIC_STATEMENT],
            public_timeline_title="Soviet Public Defiance",
            prompt_hints=[
                "Soviet/Cuban use: public denial, accusation, or refusal under pressure.",
            ],
        ),
        ScenarioCapability(
            capability_id="cuba_air_defense_alert",
            generic_action_id="military_posture",
            title="Raise Cuban Air Defense Alert",
            category=ActionCategory.MILITARY,
            actor_types_allowed=["opposing_faction"],
            targets_allowed=["player_faction"],
            channels_allowed=[SignalChannel.MILITARY],
            required_resources={"air_defense_control": 1},
            resource_costs={"air_defense_control": 1},
            min_targets=1,
            max_targets=1,
            truth_metric_effects={"escalation_pressure": 0.1, "cuban_invasion_fear": 0.05},
            public_metric_effects={"public_alarm": 0.06},
            clock_effects={
                "command_and_control_risk": 0.14,
                "nuclear_escalation": 0.08,
            },
            relationship_effects={"trust": -0.12},
            escalation_risk=0.55,
            information_outputs=[PayloadType.MILITARY_MOVEMENT_OBSERVATION],
            signal_reliability=0.8,
            signal_leak_risk=0.18,
            signal_distortion_risk=0.24,
            prompt_hints=[
                "Cuban use: air defense alert, local readiness, risk of U-2 shootdown.",
            ],
        ),
        ScenarioCapability(
            capability_id="nato_reassurance_pressure",
            generic_action_id="private_diplomacy",
            title="Request Allied Reassurance",
            category=ActionCategory.DIPLOMATIC,
            actor_types_allowed=["allied_faction"],
            targets_allowed=["player_faction"],
            channels_allowed=[SignalChannel.PRIVATE_DIPLOMATIC],
            required_resources={"alliance_credit": 1},
            resource_costs={"alliance_credit": 1},
            min_targets=1,
            max_targets=1,
            truth_metric_effects={"alliance_cohesion": 0.04},
            public_metric_effects={"allied_confidence": 0.03},
            clock_effects={"backchannel_viability": 0.02},
            relationship_effects={"trust": 0.08},
            deescalation_potential=0.1,
            information_outputs=[PayloadType.PRIVATE_DIPLOMATIC_MESSAGE],
            signal_reliability=0.86,
            signal_leak_risk=0.1,
            signal_distortion_risk=0.12,
            prompt_hints=[
                "NATO use: private request for consultation, support, or reassurance.",
            ],
        ),

    ]
