from __future__ import annotations

from enum import Enum
import json
from typing import Any, Protocol, TypeVar

from pydantic import BaseModel, Field


class ChatRole(str, Enum):
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"


class LLMMessage(BaseModel):
    role: ChatRole
    content: str


class LLMRequest(BaseModel):
    label: str
    messages: list[LLMMessage]
    temperature: float = Field(default=0.2, ge=0.0, le=2.0)
    top_p: float = Field(default=1.0, ge=0.0, le=1.0)
    max_tokens: int = Field(default=1024, ge=1)
    response_schema_name: str | None = None
    metadata: dict[str, str | int | float | bool] = Field(default_factory=dict)


class LLMCallRecord(BaseModel):
    request: LLMRequest
    raw_response: Any
    parsed_response: Any | None = None
    validation_error: str | None = None


ResponseModelT = TypeVar("ResponseModelT", bound=BaseModel)


class LLMClient(Protocol):
    def complete_json(
        self,
        request: LLMRequest,
        response_model: type[ResponseModelT],
    ) -> ResponseModelT:
        """Return a typed JSON response for an LLM task."""


class FakeLLMClient:
    """Deterministic test double for typed LLM calls."""

    def __init__(self, responses: dict[str, Any] | list[Any] | None = None) -> None:
        self._responses = responses or {}
        self.calls: list[LLMCallRecord] = []
        self._cursor = 0

    def complete_json(
        self,
        request: LLMRequest,
        response_model: type[ResponseModelT],
    ) -> ResponseModelT:
        raw = self._next_response(request.label)
        if raw == {}:
            raw = self._compat_response(request, response_model)
        record = LLMCallRecord(request=request, raw_response=raw)
        try:
            parsed = raw if isinstance(raw, response_model) else response_model.model_validate(raw)
        except Exception as exc:
            record.validation_error = str(exc)
            self.calls.append(record)
            raise
        record.parsed_response = parsed.model_dump(mode="json")
        self.calls.append(record)
        return parsed

    def _next_response(self, label: str) -> Any:
        if isinstance(self._responses, list):
            if self._cursor >= len(self._responses):
                return {}
            raw = self._responses[self._cursor]
            self._cursor += 1
            return raw
        return self._responses.get(label, {})

    def _compat_response(
        self,
        request: LLMRequest,
        response_model: type[ResponseModelT],
    ) -> Any:
        if not isinstance(self._responses, dict):
            return {}
        if response_model.__name__ == "FactionTurnResponse":
            entity_id = _faction_entity_id_from_label(request.label)
            if not entity_id:
                return {}
            prefix = f"faction.{entity_id}"
            perception = self._responses.get(f"{prefix}.perception_update")
            debate = self._responses.get(f"{prefix}.internal_debate")
            decision = self._responses.get(f"{prefix}.faction_decision")
            if perception is None or debate is None or decision is None:
                return {}
            return {
                "perception_update": perception,
                "internal_debate": debate,
                "decision": decision,
                "self_critique": [],
            }
        if response_model.__name__ == "EventCreatorResponse":
            candidate = self._responses.get("event_creator.event_creator.candidate")
            if not isinstance(candidate, dict):
                return {}
            return {
                "public_brief": {
                    "headline": candidate.get("title", "Crisis Developments Continue"),
                    "summary": candidate.get(
                        "summary",
                        "Public reports describe continuing crisis pressure.",
                    ),
                    "public_risk_read": "Public pressure remains elevated.",
                    "safe_known_facts": [str(candidate.get("summary", ""))],
                    "public_uncertainties": [],
                    "omitted_private_topics": [],
                },
                "event_candidate": candidate,
                "major_event_relevant": True,
                "editorial_notes": ["Composed from legacy EventCandidate fixture."],
            }
        if response_model.__name__ == "SignalDistortionResponse":
            context = _request_visible_context(request)
            original = str(context.get("original_content", "A report is unclear."))
            kind = str(context.get("kind", "distorted"))
            return {
                "observed_content": _fallback_distortion(original, kind),
                "distortion_note": "Generated by FakeLLMClient compatibility fallback.",
            }
        return {}


def _faction_entity_id_from_label(label: str) -> str:
    prefix = "faction."
    suffix = ".turn"
    if not label.startswith(prefix) or not label.endswith(suffix):
        return ""
    return label[len(prefix) : -len(suffix)]


def _request_visible_context(request: LLMRequest) -> dict[str, Any]:
    for message in request.messages:
        marker = "Visible context JSON:\n"
        if marker not in message.content:
            continue
        start = message.content.index(marker) + len(marker)
        end = message.content.find("\n\nTask:\n", start)
        raw_json = message.content[start:] if end == -1 else message.content[start:end]
        try:
            parsed = json.loads(raw_json)
        except json.JSONDecodeError:
            return {}
        return parsed if isinstance(parsed, dict) else {}
    return {}


def _fallback_distortion(original: str, kind: str) -> str:
    if kind == "contradictory":
        return f"Conflicting sources dispute the report: {original}"
    return f"Garbled channel report leaves this partly unclear: {original}"
